// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMpRMm3XN6t3yP2lxLuZEyNJ_-dDGBb9k',
    appId: '1:667993774787:web:6b87febf97c2246e076076',
    messagingSenderId: '667993774787',
    projectId: 'checkin-60557',
    authDomain: 'checkin-60557.firebaseapp.com',
    storageBucket: 'checkin-60557.appspot.com',
    measurementId: 'G-JM5Q3GW5TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA76EYM1BsLKuBq1x_hSPuh_Zm-8cQU4-8',
    appId: '1:667993774787:android:c909541812b8aed7076076',
    messagingSenderId: '667993774787',
    projectId: 'checkin-60557',
    storageBucket: 'checkin-60557.appspot.com',
  );
}
